### ISSUE TITLE
Getting this error in DataBase Operations

### ISSUE THREAD

**Issue by Anish-T-GitHub** [davidmartos96/sqflite_sqlcipher#92]
SqfliteSqlCipherDatabaseFactoryImpl.wrapDatabaseException (package:sqflite_sqlcipher/src/factory_sql_cipher_impl.dart:44)
<asynchronous suspension>
#1      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:485)
<asynchronous suspension>
#2      SqfliteDatabaseMixinExt.txnBeginTransaction (package:sqflite_common/src/database_mixin.dart:358)
<asynchronous suspension>
#3      SqfliteDatabaseMixin.beginTransaction (package:sqflite_common/src/database_mixin.dart:746)
<asynchronous suspension>
#4      SqfliteDatabaseMixinExt._txnTransaction (package:sqflite_common/src/database_mixin.dart:333)
<asynchronous suspension>
#5      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33)
<asynchronous suspension>
#6      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:517)
<asynchronous suspension>
#7      SqfliteDatabaseMixin.doOpen (package:sqflite_common/src/database_mixin.dart:995)
<asynchronous suspension>
#8      SqfliteDatabaseOpenHelper.openDatabase (package:sqflite_common/src/database.dart:46)
<asynchronous suspension>
#9      SqfliteDatabaseFactoryMixin.openDatabase.<anonymous closure> (package:sqflite_common/src/factory_mixin.dart:112)
<asynchronous suspension>
#10     ReentrantLock.synchronized.<anonymous closure> (package:synchronized/src/reentrant_lock.dart:37)
<asynchronous suspension>
#11     BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33)

**Comment by davidmartos96** [comment]
What's the error message? You've only shared the stack trace, which doesn't show the reason.
Please explain a bit about the error, when does it happen, is it always, some particular piece of code...

**Comment by davidmartos96** [comment]
@Anish-T-GitHub Closing for lack of information. Feel free to reopen if you share more information.
