### ISSUE TITLE
App crash with No implementation found for long net.zetetic.database.sqlcipher.SQLiteConnection.nativeOpen

### ISSUE THREAD

**Issue by sedax90** [davidmartos96/sqflite_sqlcipher#96]
I'm trying to use the package like this:
```
  Future<Database> initDb() async {
    final String path = await _getDbPath();
    log("Init database at $path");
    return await openDatabase(
      path,
      version: 1,
      password: "",
      onCreate: _onCreate,
    );
  }
```

But when I launch initDb() the app crash with:

```
E/livernet.nw.dev(28278): No implementation found for long net.zetetic.database.sqlcipher.SQLiteConnection.nativeOpen(java.lang.String, int, java.lang.String, boolean, boolean) (tried Java_net_zetetic_database_sqlcipher_SQLiteConnection_nativeOpen and Java_net_zetetic_database_sqlcipher_SQLiteConnection_nativeOpen__Ljava_lang_String_2ILjava_lang_String_2ZZ) - is the library loaded, e.g. System.loadLibrary?
E/AndroidRuntime(28278): FATAL EXCEPTION: Sqflite
E/AndroidRuntime(28278): Process: com.gullivernet.nw.dev, PID: 28278
E/AndroidRuntime(28278): java.lang.UnsatisfiedLinkError: No implementation found for long net.zetetic.database.sqlcipher.SQLiteConnection.nativeOpen(java.lang.String, int, java.lang.String, boolean, boolean) (tried Java_net_zetetic_database_sqlcipher_SQLiteConnection_nativeOpen and Java_net_zetetic_database_sqlcipher_SQLiteConnection_nativeOpen__Ljava_lang_String_2ILjava_lang_String_2ZZ) - is the library loaded, e.g. System.loadLibrary?
E/AndroidRuntime(28278): 	at net.zetetic.database.sqlcipher.SQLiteConnection.nativeOpen(Native Method)
E/AndroidRuntime(28278): 	at net.zetetic.database.sqlcipher.SQLiteConnection.open(SQLiteConnection.java:226)
E/AndroidRuntime(28278): 	at net.zetetic.database.sqlcipher.SQLiteConnection.open(SQLiteConnection.java:202)
E/AndroidRuntime(28278): 	at net.zetetic.database.sqlcipher.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:475)
E/AndroidRuntime(28278): 	at net.zetetic.database.sqlcipher.SQLiteConnectionPool.open(SQLiteConnectionPool.java:189)
E/AndroidRuntime(28278): 	at net.zetetic.database.sqlcipher.SQLiteConnectionPool.open(SQLiteConnectionPool.java:181)
E/AndroidRuntime(28278): 	at net.zetetic.database.sqlcipher.SQLiteDatabase.openInner(SQLiteDatabase.java:1028)
E/AndroidRuntime(28278): 	at net.zetetic.database.sqlcipher.SQLiteDatabase.open(SQLiteDatabase.java:1013)
E/AndroidRuntime(28278): 	at net.zetetic.database.sqlcipher.SQLiteDatabase.openDatabase(SQLiteDatabase.java:840)
E/AndroidRuntime(28278): 	at net.zetetic.database.sqlcipher.SQLiteDatabase.openDatabase(SQLiteDatabase.java:812)
E/AndroidRuntime(28278): 	at com.davidmartos96.sqflite_sqlcipher.Database.openWithFlags(Database.java:61)
E/AndroidRuntime(28278): 	at com.davidmartos96.sqflite_sqlcipher.Database.openWithFlags(Database.java:54)
E/AndroidRuntime(28278): 	at com.davidmartos96.sqflite_sqlcipher.Database.open(Database.java:35)
E/AndroidRuntime(28278): 	at com.davidmartos96.sqflite_sqlcipher.SqfliteSqlCipherPlugin$6.run(SqfliteSqlCipherPlugin.java:797)
E/AndroidRuntime(28278): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(28278): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(28278): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(28278): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(28278): 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by davidmartos96** [comment]
@sedax90  Could you try running the example app in this repository?
Also, what's the model of the Android device you are using?

Native libraries should be loaded when attaching the Flutter engine

![image](https://github.com/davidmartos96/sqflite_sqlcipher/assets/22084723/c499a1d4-c4c2-4199-ae7e-49b6ba4cf0aa)

**Comment by sedax90** [comment]
I'm actually trying on Samsung A51, I think the problem may be that I have to import a dependency which in turn imports libsqlcipher.so, and to start it I have to add in the build.gradle:

```
    packagingOptions {
        pickFirst 'lib/arm64-v8a/libsqlcipher.so'
        pickFirst 'lib/armeabi-v7a/libsqlcipher.so'
        pickFirst 'lib/x86/libsqlcipher.so'
        pickFirst 'lib/x86_64/libsqlcipher.so'
    }
```

I wouldn't know how to make them coexist though

**Comment by davidmartos96** [comment]
@sedax90 If 2 dependencies are adding the native libraries then yes, that could be the reason. You need to let Android Studio know which one you want.

As long as the SQLCipher version in this package (latest) and the one in your other dependency are compatible it should be fine to  make the 2 dependencies coexist

**Comment by sedax90** [comment]
the supplier tells me that the version used by them is 4.3.0, how can I specify which version I want?

**Comment by davidmartos96** [comment]
@sedax90 You could fork and update the dependeny in the gradle files and the podspec files for ios/macos.
In any case, latest version of sqlcipher in this package should be backwards compatible with 4.3.0. So unless there are hard requirements, you could use the libraries provided in this package.
